# Generated by Django 3.2 on 2021-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(db_column='u_id', max_length=20)),
                ('u_nick', models.CharField(db_column='u_nick', max_length=10)),
                ('u_pwd', models.CharField(db_column='u_pwd', max_length=20)),
                ('u_name', models.CharField(db_column='u_name', max_length=20)),
                ('u_age', models.IntegerField(db_column='u_age')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
