# Generated by Django 3.2 on 2021-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('p_id', models.AutoField(db_column='p_id', primary_key=True, serialize=False)),
                ('u_id', models.CharField(db_column='u_id', max_length=20)),
                ('p_name', models.CharField(db_column='p_name', max_length=20)),
                ('p_addr', models.CharField(db_column='p_addr', max_length=100)),
                ('p_cap', models.IntegerField(db_column='p_cap')),
            ],
            options={
                'db_table': 'parking',
                'managed': False,
            },
        ),
    ]
