# Generated by Django 3.2 on 2021-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_id', models.IntegerField(db_column='pf_id')),
                ('p_id', models.IntegerField(db_column='p_id')),
                ('pf_floor', models.IntegerField(db_column='pf_floor')),
                ('pf_space', models.IntegerField(db_column='pf_space')),
                ('pf_data', models.IntegerField(db_column='pf_data')),
            ],
            options={
                'db_table': 'parking_floor',
                'managed': False,
            },
        ),
    ]
